// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRAaXz3MfkHaTIzFJFogYBeTPw3CWaCh4',
    appId: '1:541257251733:web:f34265d62588ebed19d49c',
    messagingSenderId: '541257251733',
    projectId: 'workout-tracker-b4456',
    authDomain: 'workout-tracker-b4456.firebaseapp.com',
    databaseURL: 'https://workout-tracker-b4456-default-rtdb.firebaseio.com',
    storageBucket: 'workout-tracker-b4456.appspot.com',
    measurementId: 'G-R4317PV2GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVO0_JI6csEo0-T6AFvlNB_k28yCivPHc',
    appId: '1:541257251733:android:ee75dd6eece76e4919d49c',
    messagingSenderId: '541257251733',
    projectId: 'workout-tracker-b4456',
    databaseURL: 'https://workout-tracker-b4456-default-rtdb.firebaseio.com',
    storageBucket: 'workout-tracker-b4456.appspot.com',
  );

}